spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/streaming_db
    username: streaminho
    password: streaminho
jwt:
  secret: 1234secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE