spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/streaming_db
    username: streaminho
    password: streaminho
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      enabled: false

jwt:
  secret: eDSfwfHkssE4xBuBepPqXheEhDhfW99pmZPxcMDo5HA

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE